# Generated by Django 5.2.3 on 2025-06-19 17:08

import django.db.models.deletion
from django.db import migrations, models


def add_creative_fields(apps, schema_editor):
    CreativeField = apps.get_model('profiles', 'CreativeField')
    fields = [
        'Photography',
        'Fashion Design',
        'Cinematography',
        'Music',
        'Graphic Design',
        'Illustration',
        'Animation',
        'Video Editing',
        'UX/UI Design',
    ]
    for name in fields:
        CreativeField.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('profile_picture', models.ImageField(blank=True, default='profiles/default.jpg', upload_to='profiles/')),
                ('bio', models.TextField()),
                ('creative_fields', models.ManyToManyField(to='profiles.creativefield')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_links', to='profiles.profile')),
            ],
        ),
        migrations.RunPython(add_creative_fields),
    ]
